server:
  port: 8085

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
