spring:
  jms:
    template:
      default-destination: kit.tacocloud.order.queue
  artemis:
    host: localhost
    port: 61616
    user: kit
    password: testPass
    embedded:
      enabled: false