spring:
  main:
    web-application-type: none

tacocloud:
  api:
    url: http://localhost:8085/orders/fromEmail

  email:
    host: imap.yandex.ru:993
    mailbox: inbox
    username: dmitrytesttest
    password: changeMe
    poll-rate: 10000
server:
  port: 8087
