spring:
  main:
    web-application-type: none

tacocloud:
  api:
    url: http://localhost:8085/orders/fromEmail

  email:
    host: imap.tacocloud.com
    mailbox: KITBOX
    username: kit-flow
    password: 123
    poll-rate: 10000

