server:
  port: 8083

---
spring:
  profiles: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: kit
    password: testPass
    embedded:
      enabled: false
  devtools:
    livereload:
      enabled: false

---
spring:
  profiles: kafka-listener

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: kit.tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos